# Generated by Django 5.0.7 on 2024-07-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='many',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('num', models.IntegerField()),
                ('nameid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='nameid',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
