# Generated by Django 5.0.7 on 2024-07-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_many_contact_nameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='many',
            name='nbr',
            field=models.IntegerField(default=0),
        ),
    ]
